---
- name: set vars
  set_fact:
    download_base_url: https://download.docker.com/linux/ubuntu/dists/{{ ansible_distribution_release }}/pool/stable/amd64
    packages:
    - containerd.io_{{ containerd_version }}-1_amd64.deb
    - docker-ce-cli_{{ docker_version }}~3-0~ubuntu-{{ ansible_distribution_release }}_amd64.deb
    - docker-ce_{{ docker_version }}~3-0~ubuntu-{{ ansible_distribution_release }}_amd64.deb
    dest_path: "{{ remote_path | d('/tmp') }}"

- name: install docker
  include_role:
    name: install-1.0.5
  vars:
    opts:
      dest_path: "{{ dest_path }}"
      local_path: "{{ ansible_distribution_release }}"
      pkg_name: "{{ pkg.split('_').0 }}"
      pkg_version: "{{ pkg.split('_').1 | regex_search('^[0-9.]+') }}"
      pkg_type: deb
      pkg_url: "{{ download_base_url }}/{{ pkg }}"
  loop: "{{ packages }}"
  loop_control:
    loop_var: pkg

- name: Install Docker
  apt:
    deb: "{{ dest_path }}/{{ pkg.split('_').0 }}-{{ pkg.split('_').1 | regex_search('^[0-9.]+') }}.deb"
    policy_rc_d: 101
    state: present
  loop: "{{ packages }}"
  loop_control:
    loop_var: pkg

- name: prepare config dir
  file:
    path: /etc/docker
    state: directory

- name: prepare config file
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {}

- name: mask docker service
  systemd:
    name: docker
    enabled: no
    masked: yes
    state: stopped
