---
- name: set up default home var
  set_fact:
    default_dest_dir: "/opt/{{ opts.pkg_name }}/{{ opts.pkg_version }}/"
  when: opts.pkg_version is defined

- name: set up variables
  set_fact:
    dest_path: "{{ opts.dest_path | d(default_dest_dir) }}"
    pkg_name: "{{ opts.pkg_name }}"
    pkg_type: "{{ opts.pkg_type | d('') }}"
    pkg_version: "{{ opts.pkg_version | d('') }}"
    extracts: "{{ opts.extracts | d(false) }}"
    extra_opts: "{{ opts.extra_opts | d(['--strip-components=1'] if opts.pkg_type == 'tgz' else []) }}"
    creates: "{{ opts.creates | d('') }}"
    parent_role_name: "{{ ansible_parent_role_names[0] | regex_replace('-[0-9.]+$', '') }}"
    target_owner: "{{ opts.target_owner | d('root') }}"
    target_group: "{{ opts.target_group | d('root') }}"

- name: set other variables
  set_fact:
    local_path: "{{ local_cache_path }}/{{ parent_role_name }}/{{ opts.local_path + '/' if opts.local_path is defined else '' }}{{ pkg_name }}{{ '-' + pkg_version if pkg_version else '' }}{{ '.' + pkg_type if pkg_type else '' }}"

- name: install tools
  apt:
    name: ['unzip']
    state: present
    update_cache: no
  when:
  - extracts
  - pkg_type == 'zip'

- name: check if package file exists
  stat:
    path: "{{ local_path }}"
  register: cached_file
  run_once: True
  delegate_to: localhost

- name: prepare local dir
  file:
    dest: "{{ local_path | dirname }}"
    state: directory
  delegate_to: localhost
  when:
  - cached_file.stat.exists == False

- name: download package - {{ pkg_name }}
  get_url:
    url: "{{ opts.pkg_url }}"
    dest: "{{ local_path }}"
  delegate_to: localhost
  run_once: True
  when:
  - cached_file.stat.exists == False

- name: Prepare directories - {{ pkg_name }}
  file:
    path: "{{ dest_path if extracts or dest_path[-1] == '/' else dest_path | dirname }}"
    owner: "{{ target_owner }}"
    group: "{{ target_group }}"
    state: directory

- name: extract package - {{ pkg_name }}
  unarchive:
    src: "{{ local_path }}"
    dest: "{{ dest_path }}"
    owner: "{{ target_owner }}"
    group: "{{ target_group }}"
    creates: "{{ dest_path | regex_replace('/*$', '') }}/{{ creates }}"
    extra_opts: "{{ extra_opts }}"
  when:
  - extracts

- name: set permissions - {{ pkg_name }}
  file:
    path: "{{ dest_path }}"
    owner: "{{ target_owner }}"
    group: "{{ target_group }}"
    recurse: yes
  when:
  - extracts

- name: transfer package - {{ pkg_name }}
  copy:
    src: "{{ local_path }}"
    dest: "{{ dest_path }}"
    mode: "{{ opts.file_mode | d('644') }}"
  when:
  - extracts == False

- name: create symbolic link - {{ pkg_name }}
  file:
    src: "{{ pkg_version }}"
    dest: "/opt/{{ pkg_name }}/current"
    state: link
  when: dest_path == default_dest_dir

- name: add bin path to PATH
  copy:
    dest: /etc/profile.d/{{ pkg_name }}-path.sh
    content: PATH={{ '/opt/' + pkg_name + '/current' if dest_path == default_dest_dir else dest_path | regex_replace('/*$', '') }}/{{ opts.bin_path }}:$PATH
  when: opts.bin_path is defined

- name: create bin symbolic links - {{ pkg_name }}
  file:
    src: "{{ '/opt/' + pkg_name + '/current' if dest_path == default_dest_dir else dest_path }}{{ '/' + bin_link.src if bin_link.src else '' }}"
    dest: "{{ bin_link.dest | d('/usr/bin/' + (bin_link.src | basename)) }}"
    force: yes
    state: link
  loop: "{{ opts.bin_links }}"
  loop_control:
    loop_var: bin_link
  when: opts.bin_links is defined
