---
- name: create service user
  include_role:
    name: create-service-user-1.0.0
  vars:
    svc_user: etcd

- name: install etcd
  include_role:
    name: install-1.0.2
  vars:
    opts:
      pkg_name: etcd
      pkg_version: "{{ etcd_version }}"
      pkg_type: tgz
      pkg_url: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
      extracts: yes
      creates: etcd
      bin_path:

- name: install systemd file
  copy:
    src: files/lib/systemd/system/
    dest: /lib/systemd/system/
    owner: root
    group: root
    mode: preserve

- name: mask etcd service
  systemd:
    name: etcd
    enabled: no
    masked: yes
    state: stopped

- name: install sample conf files
  copy:
    src: files/opt/app/
    dest: /opt/app/
    owner: root
    group: svc
    mode: preserve
