---
- name: compile
  shell: |
    compileTmpls() {
      local commonFiles="$(ls {{ role_path }}/files/etc/confd/templates/*)"
      local srcFiles="$commonFiles ${@:2}" destFile=$1
      for tmpl in $srcFiles; do
        (cat $tmpl; echo) >> $destFile
      done
    }

    set -euo pipefail

    parentRolePath="{{ ansible_parent_role_paths[0] }}"
    parentRoleName="{{ ansible_parent_role_names[0] }}"
    srcRootDir="$parentRolePath/files/etc/confd/templates"
    test -d "$srcRootDir" || exit 1

    destDir={{ local_cache_path }}/$parentRoleName/confd/templates
    mkdir -p $destDir
    rm -rf $destDir/*
    for srcDir in $(ls -d $srcRootDir/*/); do
      compileTmpls $destDir/$(basename $srcDir).tmpl $(ls $srcDir*.tmpl)
    done
    find $srcRootDir -maxdepth 1 -name '*.tmpl' -exec cp {} $destDir/ \;
  args:
    executable: /bin/bash
  delegate_to: localhost
  run_once: True

- name: prepare confd dir
  file:
    path: /opt/app/current/conf/confd/
    state: directory

- name: install
  copy:
    src: "{{ path.src }}/"
    dest: /opt/app/current/conf/confd/{{ path.dest }}/
    owner: root
    group: root
  loop:
  - src: "{{ ansible_parent_role_paths[0] }}/files/etc/confd/conf.d"
    dest: conf.d
  - src: "{{ local_cache_path }}/{{ ansible_parent_role_names[0] }}/confd/templates"
    dest: templates
  loop_control:
    loop_var: path

- name: link confd files
  file:
    src: /opt/app/current/conf/confd/{{ item | dirname | basename }}/{{ item | basename }}
    dest: /etc/confd/{{ item | dirname | basename }}/{{ item | basename }}
    owner: root
    state: link
  with_fileglob:
  - "{{ ansible_parent_role_paths[0] }}/files/etc/confd/conf.d/*"
  - "{{ local_cache_path }}/{{ ansible_parent_role_names[0] }}/confd/templates/*"
