---
- name: compile
  shell: |
    compileTmpls() {
      local commonFiles="$(ls {{ role_path }}/files/etc/confd/templates/*)"
      local srcFiles="$commonFiles ${@:2}" destFile=$1
      for tmpl in $srcFiles; do
        (cat $tmpl; echo) >> $destFile
      done
    }

    set -euo pipefail

    parentRolePath="{{ ansible_parent_role_paths[0] }}"
    srcRootDir="$parentRolePath/files/etc/confd/templates"
    test -d "$srcRootDir" || exit 1
    destDir=$parentRolePath/files/tmp/confd/templates
    mkdir -p $destDir
    rm -rf $destDir/*
    for srcDir in $(ls -d $srcRootDir/*/); do
      compileTmpls $destDir/$(basename $srcDir).tmpl $(ls $srcDir*.tmpl)
    done
    find $srcRootDir -maxdepth 1 -name '*.tmpl' -exec cp {} $destDir/ \;
  args:
    executable: /bin/bash
  delegate_to: localhost
  run_once: True

- name: install
  copy:
    src: "{{ ansible_parent_role_paths[0] }}/files/{{ path.src }}/"
    dest: /etc/confd/{{ path.dest }}/
    owner: root
    group: root
  loop:
  - src: etc/confd/conf.d
    dest: conf.d
  - src: tmp/confd/templates
    dest: templates
  loop_control:
    loop_var: path
