---
- name: set up variables
  set_fact:
    app_agent_version: 1.0.6

- name: install packages
  include_role:
    name: install-1.0.5
  vars:
    opts:
      pkg_name: app-agent
      pkg_version: "{{ app_agent_version }}"
      dest_path: /tmp/app-agent
      pkg_url: https://github.com/QingCloudAppcenter/AppcenterAgent/releases/download/v{{ app_agent_version }}/app-agent-linux-amd64.tar.gz
      pkg_type: tgz
      extracts: yes
      creates: bin

- name: install app agent
  shell:
    cmd: ./install.sh
    chdir: /tmp/app-agent
    creates: /opt/qingcloud/app-agent/bin/confd

- name: make logging files persistent
  blockinfile:
    path: /etc/init.d/confd
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: "^start"
    block: |
      # indent
        if [ ! -L "$PROG_PATH/log" ]; then
          persistentDir=/data/app-agent/logs
          mkdir -p $persistentDir
          rsync -aAX $PROG_PATH/log/ $persistentDir/
          rm -rf $PROG_PATH/log
          ln -s $persistentDir $PROG_PATH/log
        fi

- name: adjust logrotate
  replace:
    path: /etc/logrotate.d/app-agent
    regexp: '^(\s+size).*'
    replace: '\1 2M'
